'use client';
import { ReactNode, useEffect, useState } from 'react';
import '../globals.css';
import Navbar from '@/components/Navbar';
import { Toaster } from 'sonner';
import { useTheme } from 'next-themes';

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
// is-dark
const MainLayout = ({ children }) => {
	const [customTheme, setCustomTheme] = useState('');
	const { theme, setTheme } = useTheme();
	useEffect(() => {
		if (window) {
			setCustomTheme(localStorage.getItem('theme') ?? '');
		}
	}, []);

	const toggleTheme = () => {
		const val = localStorage.getItem('theme');
		if (val == 'is-dark') {
			localStorage.removeItem('theme');
			setCustomTheme('');
			// setTheme("light");
		} else {
			localStorage.setItem('theme', 'is-dark');
			setCustomTheme('is-dark');
			// setTheme("dark");
		}
	};
	return (
		<div
			className={`nk-body ${customTheme} overflow-x-hidden`}
			data-menu-collapse='lg'
		>
			<div className='nk-mask bg-pattern-dot-white-sm' />
			<Navbar toggleTheme={toggleTheme} />
			<div className='flex-1'>{children}</div>
			<footer className='nk-footer pt-4 pt-lg-7'>
				<div className='container'>
					<hr className='border-opacity-25 border-white m-0' />
					<div className='py-5'>
						<div className='row'>
							<div className='col-md'>
								<p className='mb-2 mb-md-0'>© 2025 Smart Resume Matcher.</p>
							</div>
							<div className='col-md'>
								<ul className='btn-list btn-list-inline g-1 justify-content-start justify-content-md-end'>
									<li>
										<a
											className='link-base'
											href='https://t.me/sam_abdullaev'
											rel='noopener noreferrer'
											target='_blank'
										>
											<em className='icon fs-3 ni ni-telegram-circle' />
										</a>
									</li>
									<li>
										<a
											className='link-base'
											href='https://www.linkedin.com/in/samabdullaev/'
											rel='noopener noreferrer'
											target='_blank'
										>
											<em className='icon fs-3 ni ni-linkedin-round' />
										</a>
									</li>
									<li>
										{/* <a className="link-base" href="#">
                  <em className="icon fs-3 ni ni-instagram" />
                </a> */}
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</footer>
			<Toaster
				toastOptions={{
					classNames: {
						toast: 'custom-toast animate-sparkle',
						title: 'custom-toast-title',
						description: 'custom-toast-desc',
						actionButton: 'custom-toast-action',
						cancelButton: 'custom-toast-cancel',
						closeButton: 'custom-toast-close',
					},
				}}
				position='top-center'
			/>
		</div>
	);
};

export default MainLayout;
